import { Project } from '@/types/orchestrator';
import { listArtifacts } from '@/app/api/lib/project-utils';
import { logger } from '@/lib/logger';

/**
 * Generate HANDOFF.md for LLM-based code generation
 */
export class HandoffGenerator {
  generateHandoff(slug: string, projectMetadata: Record<string, any>): string {
    const stackChoice = projectMetadata.stack_choice || 'custom';
    const name = projectMetadata.name || 'Unnamed Project';

    // Collect artifacts from all completed phases
    const allPhases = ['ANALYSIS', 'STACK_SELECTION', 'SPEC', 'DEPENDENCIES', 'SOLUTIONING'];
    const artifacts: Record<string, string> = {};

    for (const phase of allPhases) {
      const phaseArtifacts = listArtifacts(slug, phase);
      for (const artifact of phaseArtifacts) {
        artifacts[`${phase}/${artifact.name}`] = artifact.content || '';
      }
    }

    // Generate markdown handoff document
    const handoff = `# ${name} - Project Handoff

## Overview
This is an auto-generated handoff document containing all project specifications, architecture decisions, and implementation guidance generated by the Spec-Driven Platform.

**Generated:** ${new Date().toISOString()}
**Stack Choice:** ${stackChoice}
**Project Slug:** ${slug}

---

## Reading Order

This document should be read in the following order for best understanding:

1. **constitution.md** - Project philosophy and guiding principles
2. **project-brief.md** - High-level overview and context
3. **personas.md** - User personas and target audience
4. **PRD.md** - Product requirements and features
5. **data-model.md** - Database schema and data structures
6. **api-spec.json** or **api-spec.md** - API endpoints and contracts
7. **DEPENDENCIES.md** - Required packages and dependencies
8. **architecture.md** - System architecture and design patterns
9. **epics.md** - Feature epics and logical groupings
10. **tasks.md** - Detailed implementation tasks with dependencies

---

## Project Context

### Artifact Manifest

\`\`\`
${Object.keys(artifacts)
  .map(name => `- ${name}`)
  .join('\n')}
\`\`\`

---

## LLM Code Generation Prompt

Use the following prompt with your preferred LLM (Claude, GPT-4, Gemini, etc.) to generate production-ready code:

\`\`\`
You are an expert full-stack software engineer tasked with implementing a complete project based on comprehensive specifications.

**Project Name:** ${name}
**Technology Stack:** ${stackChoice}

Please review the attached specifications in the order listed above, then:

1. **Understand the requirements** - Read through all specification documents
2. **Validate consistency** - Ensure all documents are consistent and complete
3. **Generate code** - Create production-ready code following all specifications
4. **Structure properly** - Organize code with proper folder structure and conventions
5. **Add documentation** - Include inline comments and README files
6. **Consider scalability** - Implement with future growth in mind
7. **Security first** - Follow security best practices throughout
8. **Testing ready** - Structure code to be testable with unit, integration, and E2E tests

**Key constraints:**
- Follow the exact architecture described in architecture.md
- Implement all API endpoints in api-spec
- Include all database tables from data-model
- Satisfy all requirements in PRD.md
- Use the specified technology stack
- Follow security baseline requirements

**Output:**
Return a complete, production-ready codebase with all source files, configuration, and documentation.
\`\`\`

---

## Specification Documents

### Constitution

\`\`\`markdown
${artifacts['ANALYSIS/constitution.md'] || 'Constitution document not available'}
\`\`\`

### Project Brief

\`\`\`markdown
${artifacts['ANALYSIS/project-brief.md'] || 'Project brief document not available'}
\`\`\`

### Personas

\`\`\`markdown
${artifacts['ANALYSIS/personas.md'] || 'Personas document not available'}
\`\`\`

### Product Requirements Document (PRD)

\`\`\`markdown
${artifacts['SPEC/PRD.md'] || 'PRD document not available'}
\`\`\`

### Data Model

\`\`\`markdown
${artifacts['SPEC/data-model.md'] || 'Data model document not available'}
\`\`\`

### API Specification

\`\`\`json
${artifacts['SPEC/api-spec.json'] || artifacts['SPEC/api-spec.md'] || 'API specification not available'}
\`\`\`

### Dependencies

\`\`\`markdown
${artifacts['DEPENDENCIES/DEPENDENCIES.md'] || 'Dependencies document not available'}
\`\`\`

### Architecture

\`\`\`markdown
${artifacts['SOLUTIONING/architecture.md'] || 'Architecture document not available'}
\`\`\`

### Epics

\`\`\`markdown
${artifacts['SOLUTIONING/epics.md'] || 'Epics document not available'}
\`\`\`

### Tasks

\`\`\`markdown
${artifacts['SOLUTIONING/tasks.md'] || 'Tasks document not available'}
\`\`\`

---

## Next Steps

1. **Download** - Download the complete ZIP archive containing all specification files
2. **Review** - Study the specifications thoroughly
3. **Generate** - Use this HANDOFF.md with your preferred LLM to generate code
4. **Customize** - Modify generated code as needed for your specific requirements
5. **Test** - Write comprehensive tests for all functionality
6. **Deploy** - Follow deployment guidelines in architecture.md

---

## Support & Questions

For questions about the specifications or the Spec-Driven Platform:
- Review the CLAUDE.md file in the original project
- Check the ORCHESTRATOR_DESIGN.md for detailed workflow information
- Refer to individual specification documents for detailed guidance

Generated by **Spec-Driven Platform** - Transform ideas into production-ready projects.
`;

    return handoff;
  }
}
