// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { Project } from '@/types/orchestrator';
import { listArtifacts } from '@/app/api/lib/project-utils';
import { logger } from '@/lib/logger';
import { readFileSync, existsSync } from 'fs';
import { resolve } from 'path';

/**
 * Generate HANDOFF.md and README.md for LLM-based code generation
 */
export class HandoffGenerator {
  /**
   * Generate README.md - a quick-start guide for the project
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  async generateReadme(slug: string, projectMetadata: Record<string, any>, artifacts: Record<string, string>): Promise<string> {
    const stackChoice = projectMetadata.stack_choice || 'custom';
    const name = projectMetadata.name || 'Unnamed Project';
    const description = projectMetadata.description || '';

    // Extract key info from artifacts
    const projectBrief = artifacts['ANALYSIS/project-brief.md'] || '';
    const architecture = artifacts['SOLUTIONING/architecture.md'] || '';
    
    // Try to extract executive summary from project brief
    let executiveSummary = '';
    const summaryMatch = projectBrief.match(/##?\s*Executive Summary[\s\S]*?(?=##|\n\n\n|$)/i);
    if (summaryMatch) {
      executiveSummary = summaryMatch[0].replace(/##?\s*Executive Summary\s*/i, '').trim().slice(0, 500);
    } else {
      executiveSummary = description || 'A project generated by Spec-Driven Platform.';
    }

    // Extract tech stack info
    const stackDescriptions: Record<string, string> = {
      'web_application': 'Web Application (Monolithic Full-Stack)',
      'mobile_application': 'Mobile Application (Cross-Platform Native)',
      'api_first_platform': 'API-First Platform (Headless/Multi-Client)',
      // Legacy support
      'nextjs_only_expo': 'Next.js 14 + Expo (React Native)',
      'hybrid_nextjs_fastapi_expo': 'Next.js 14 + FastAPI + Expo',
      'monolithic_fullstack': 'Web Application (Monolithic Full-Stack)',
      'decoupled_services': 'API-First Platform (Headless/Multi-Client)'
    };
    const techStack = stackDescriptions[stackChoice] || stackChoice;

    return `# ${name}

${executiveSummary}

## Tech Stack

- **Stack**: ${techStack}
- **Generated**: ${new Date().toISOString().split('T')[0]}

## Quick Start

\`\`\`bash
# Clone or download the project
git clone <repository-url>
cd ${slug}

# Install dependencies
pnpm install

# Set up environment variables
cp .env.example .env.local
# Edit .env.local with your values

# Run database migrations (if applicable)
pnpm db:migrate

# Start development server
pnpm dev
\`\`\`

## Project Structure

\`\`\`
${slug}/
├── HANDOFF.md          # Complete project handoff for LLM code generation
├── README.md           # This file
├── specs/              # All specification documents
│   ├── ANALYSIS/       # Analysis phase outputs
│   ├── SPEC/           # Specification phase outputs
│   ├── DEPENDENCIES/   # Dependency definitions
│   └── SOLUTIONING/    # Architecture and task breakdown
└── (generated code)    # Use HANDOFF.md with an LLM to generate
\`\`\`

## Documentation

| Document | Description |
|----------|-------------|
| [HANDOFF.md](./HANDOFF.md) | Complete handoff document for LLM code generation |
| [constitution.md](./specs/ANALYSIS/constitution.md) | Project guiding principles |
| [project-brief.md](./specs/ANALYSIS/project-brief.md) | Project overview and requirements |
| [PRD.md](./specs/SPEC/PRD.md) | Product Requirements Document |
| [architecture.md](./specs/SOLUTIONING/architecture.md) | System architecture |
| [tasks.md](./specs/SOLUTIONING/tasks.md) | Implementation task breakdown |

## Code Generation

To generate the implementation code, use the HANDOFF.md with your preferred LLM:

1. Open HANDOFF.md in your editor
2. Copy the entire content
3. Paste into Claude, GPT-4, or Gemini
4. Request code generation following the specifications

## License

This project was generated using the Spec-Driven Platform.

---

*Generated by [Spec-Driven Platform](https://spec-driven.dev)*
`;
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  async generateHandoff(slug: string, projectMetadata: Record<string, any>): Promise<string> {
    const stackChoice = projectMetadata.stack_choice || 'custom';
    const name = projectMetadata.name || 'Unnamed Project';

    // Collect artifacts from all completed phases
    const allPhases = ['ANALYSIS', 'STACK_SELECTION', 'SPEC', 'DEPENDENCIES', 'SOLUTIONING'];
    const artifacts: Record<string, string> = {};

    for (const phase of allPhases) {
      const phaseArtifacts = await listArtifacts(slug, phase);
      for (const artifact of phaseArtifacts) {
        try {
          const artifactPath = resolve(process.cwd(), 'projects', slug, 'specs', phase, 'v1', artifact.name);
          if (existsSync(artifactPath)) {
            const content = readFileSync(artifactPath, 'utf8');
            artifacts[`${phase}/${artifact.name}`] = content;
          } else {
            artifacts[`${phase}/${artifact.name}`] = '';
          }
        } catch (error) {
          const err = error instanceof Error ? error : new Error(String(error));
          logger.warn(`Failed to read artifact ${artifact.name}: ${err.message}`, {
            errorName: err.name,
            stack: err.stack
          });
          artifacts[`${phase}/${artifact.name}`] = '';
        }
      }
    }

    // Generate markdown handoff document
    const handoff = `# ${name} - Project Handoff

## Overview
This is an auto-generated handoff document containing all project specifications, architecture decisions, and implementation guidance generated by the Spec-Driven Platform.

**Generated:** ${new Date().toISOString()}
**Stack Choice:** ${stackChoice}
**Project Slug:** ${slug}

---

## Reading Order

This document should be read in the following order for best understanding:

1. **constitution.md** - Project philosophy and guiding principles
2. **project-brief.md** - High-level overview and context
3. **personas.md** - User personas and target audience
4. **PRD.md** - Product requirements and features
5. **data-model.md** - Database schema and data structures
6. **api-spec.json** or **api-spec.md** - API endpoints and contracts
7. **DEPENDENCIES.md** - Required packages and dependencies
8. **architecture.md** - System architecture and design patterns
9. **epics.md** - Feature epics and logical groupings
10. **tasks.md** - Detailed implementation tasks with dependencies

---

## Project Context

### Artifact Manifest

\`\`\`
${Object.keys(artifacts)
  .map(name => `- ${name}`)
  .join('\n')}
\`\`\`

---

## LLM Code Generation Prompt

Use the following prompt with your preferred LLM (Claude, GPT-4, Gemini, etc.) to generate production-ready code:

\`\`\`
You are an expert full-stack software engineer tasked with implementing a complete project based on comprehensive specifications.

**Project Name:** ${name}
**Technology Stack:** ${stackChoice}

Please review the attached specifications in the order listed above, then:

1. **Understand the requirements** - Read through all specification documents
2. **Validate consistency** - Ensure all documents are consistent and complete
3. **Generate code** - Create production-ready code following all specifications
4. **Structure properly** - Organize code with proper folder structure and conventions
5. **Add documentation** - Include inline comments and README files
6. **Consider scalability** - Implement with future growth in mind
7. **Security first** - Follow security best practices throughout
8. **Testing ready** - Structure code to be testable with unit, integration, and E2E tests

**Key constraints:**
- Follow the exact architecture described in architecture.md
- Implement all API endpoints in api-spec
- Include all database tables from data-model
- Satisfy all requirements in PRD.md
- Use the specified technology stack
- Follow security baseline requirements

**Output:**
Return a complete, production-ready codebase with all source files, configuration, and documentation.
\`\`\`

---

## Specification Documents

### Constitution

\`\`\`markdown
${artifacts['ANALYSIS/constitution.md'] || 'Constitution document not available'}
\`\`\`

### Project Brief

\`\`\`markdown
${artifacts['ANALYSIS/project-brief.md'] || 'Project brief document not available'}
\`\`\`

### Personas

\`\`\`markdown
${artifacts['ANALYSIS/personas.md'] || 'Personas document not available'}
\`\`\`

### Product Requirements Document (PRD)

\`\`\`markdown
${artifacts['SPEC/PRD.md'] || 'PRD document not available'}
\`\`\`

### Data Model

\`\`\`markdown
${artifacts['SPEC/data-model.md'] || 'Data model document not available'}
\`\`\`

### API Specification

\`\`\`json
${artifacts['SPEC/api-spec.json'] || artifacts['SPEC/api-spec.md'] || 'API specification not available'}
\`\`\`

### Dependencies

\`\`\`markdown
${artifacts['DEPENDENCIES/DEPENDENCIES.md'] || 'Dependencies document not available'}
\`\`\`

### Architecture

\`\`\`markdown
${artifacts['SOLUTIONING/architecture.md'] || 'Architecture document not available'}
\`\`\`

### Epics

\`\`\`markdown
${artifacts['SOLUTIONING/epics.md'] || 'Epics document not available'}
\`\`\`

### Tasks

\`\`\`markdown
${artifacts['SOLUTIONING/tasks.md'] || 'Tasks document not available'}
\`\`\`

---

## Next Steps

1. **Download** - Download the complete ZIP archive containing all specification files
2. **Review** - Study the specifications thoroughly
3. **Generate** - Use this HANDOFF.md with your preferred LLM to generate code
4. **Customize** - Modify generated code as needed for your specific requirements
5. **Test** - Write comprehensive tests for all functionality
6. **Deploy** - Follow deployment guidelines in architecture.md

---

## Support & Questions

For questions about the specifications or the Spec-Driven Platform:
- Review the CLAUDE.md file in the original project
- Check the ORCHESTRATOR_DESIGN.md for detailed workflow information
- Refer to individual specification documents for detailed guidance

Generated by **Spec-Driven Platform** - Transform ideas into production-ready projects.
`;

    return handoff;
  }
}
