/**
 * Writing Plans Skill Adapter
 * 
 * Generates structured plans and documentation for project phases.
 */

import { SkillAdapter } from '../skill_adapter';
import { SkillContext, SkillResult, SuperpowersSkill } from '../types';

export class WritingPlansAdapter extends SkillAdapter {
  skill: SuperpowersSkill = 'writing_plans';
  
  canHandle(phase: string, context: Record<string, unknown>): boolean {
    return ['SOLUTIONING', 'SPEC_PM', 'SPEC_ARCHITECT', 'DEPENDENCIES'].includes(phase);
  }
  
  async execute(
    input: Record<string, unknown>,
    context: SkillContext
  ): Promise<SkillResult> {
    const startTime = Date.now();
    
    const { valid, errors } = this.validateInput(input, ['phaseType', 'requirements']);
    if (!valid) {
      return this.createErrorResult(errors, Date.now() - startTime);
    }
    
    const plan = this.generatePlan(input, context.phase);
    
    return this.createSuccessResult(
      {
        plan: plan.content,
        sections: plan.sections,
        tasks: plan.tasks,
        milestones: plan.milestones,
        timeline: plan.timeline,
      },
      Date.now() - startTime
    );
  }
  
  private generatePlan(
    input: Record<string, unknown>,
    phase: string
  ): {
    content: string;
    sections: string[];
    tasks: Array<{ id: string; description: string; priority: string }>;
    milestones: Array<{ name: string; criteria: string[] }>;
    timeline: string;
  } {
    const phaseType = String(input.phaseType || 'general');
    const requirements = input.requirements as Record<string, unknown>;
    
    const sections = ['Overview', 'Objectives', 'Approach', 'Deliverables', 'Timeline', 'Risks'];
    
    const tasks = [
      { id: 'TASK-001', description: 'Initial analysis and planning', priority: 'high' },
      { id: 'TASK-002', description: 'Architecture design review', priority: 'high' },
      { id: 'TASK-003', description: 'Implementation planning', priority: 'medium' },
      { id: 'TASK-004', description: 'Resource allocation', priority: 'medium' },
      { id: 'TASK-005', description: 'Risk assessment', priority: 'low' },
    ];
    
    const milestones = [
      { name: 'Planning Complete', criteria: ['All tasks defined', 'Resources allocated', 'Risks identified'] },
      { name: 'Design Approved', criteria: ['Architecture reviewed', 'Stakeholder sign-off'] },
      { name: 'Ready for Implementation', criteria: ['Plan finalized', 'Dependencies resolved'] },
    ];
    
    return {
      content: this.buildPlanContent(phaseType, requirements),
      sections,
      tasks,
      milestones,
      timeline: '4-6 weeks',
    };
  }
  
  private buildPlanContent(
    phaseType: string,
    requirements: Record<string, unknown>
  ): string {
    return `# ${phaseType} Plan

## Overview
This document outlines the plan for the ${phaseType} phase, including objectives, approach, deliverables, and timeline.

## Objectives
- Complete all required artifacts for ${phaseType}
- Ensure quality and compliance with project standards
- Deliver actionable outputs for downstream phases

## Approach
1. Review existing artifacts and requirements
2. Generate required documentation
3. Validate outputs against quality criteria
4. Iterate based on feedback

## Deliverables
- Primary artifact document
- Supporting documentation
- Validation report

## Timeline
Estimated duration: 2-4 weeks

## Risks
- Resource constraints
- Requirement changes
- Technical dependencies

---
Generated by WritingPlansAdapter
`;
  }
}
